nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/openclaw/openclaw
  tag: "latest"
  pullPolicy: IfNotPresent

# External Ollama service coordinates
ollamaNamespace: ai-model
ollamaHost: "http://ollama.ai-model.svc.cluster.local:11434"
ollamaModel: "qwen3:8b"
sandbox: 'false'

extraEnvVars: [ ]

envFrom: [ ]
# - secretRef:
#     name: openclaw-api-keys

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

persistence:
  enabled: true
  storageClass: ""
  size: 10Gi
  local:
    enabled: false
    node: node1
    path: /home/tik/data/openclaw-data/
    reclaimPolicy: Retain

networkPolicy:
  allowedIngressCIDRs:
    - 0.0.0.0/0   # restrict to your network CIDR in production

webTerminal:
  enabled: false
  readOnly: false
  resources: { }
  # credential:
  #   secretRef:
  #     name: openclaw-webterminal-secret

service:
  gatewayPort: 18789
  canvasPort: 18793
  webTerminalPort: 7681
  browserPort: 18791

nodeSelector: { }
