---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    token: AgAkHgxEwnGDvVAnBTjo+CEcuwhG9O460w/H4EaW3lyJ+nW1mVWHj8oKelaGpmRJbZ9AjE93/QkrxCTTZRY8jlWgtvVvbbYAW7QERk9EmVXHSWqDe/mmQQ2x4VSnnJ+0xoxZFBS99IlXW2pC0qa0L8EN6Jimi6l9wANX3ElZZ4L8mPFto0/tgbTqwTEyY4JxUpQWKSVRNQljpGxHEyl24YqkIonxWb5qHtqYUK84BMXyGlYWH1ZsJI8fzVhUmedcyJVfc9g6DfirVDPkFeqGXkVC4hRpgVRbr75kMAntNc+yK+hvbhvJZcyheZKy++wytgOjs4qSpgcWlxtuehMkYcHZB5Ry0eayGXU89p32hQ4qQ9Ls4/tPfMeUrE9IExvzyZsu3nAVMAbIqeW7nYzIZKywXbQU50onJbHWONg1PxjEUAOlXaZDB6Z7HwR3/TU82LqQi/jsC6lkf6FQD/1E904258kK4+y8bf1jgwoa92RC47jJftc8K2S2kvkfvWImkgOuYnT36J8rUN7Zpo8QDbI5PPe+fYhdC7Ukc80v1BHg04ThWslVCcSJUluI4/JvtkW2AIgoWbZT7IGyXdp41IaOgyGOhbHw4dBgONa3ukHiB9T0/r1FmqNH6kYDyCYgQorCaq28k4ybHIuyOPyFQHF6ishJ7OpRXCunOeAJh89+ArMUO+W+hjxCWSiWof2ezhEL2KWPyYg6Gnggp3IfN8KaSNCI6c3UhDCY2o4eKxqOKFkjcktuRClaOdwqzPCO
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
