---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    client-secret: AgBaAUMueU7hXRMEjF0BDM6TfNzfKDDO5ZhLO34x4rDmdo2XuRLx8Tlgz/VClmuRDTeeANXR6LZB4GenV5lmEZHSpbw5AENXdpOwE8EMWFYojEjk/YdCEUPFBA0kAprw4vfHI23JYvOEJ+u3J3ScdBrXqF1KZQb/c2aD684muaAXzB+zvHSCRUbrKrjFXxCMIUVAFB0TjlZgazCZJ99KTO9X1lifR/XjxxiiHnys0PIKmXszVe6RJhoRE5JkU16Z35fFBp/W6rtqoZJbTulvJvzVKb7g2djIqjuX5WT+/TGox8z2jbSd4pbFxUYq2tC7Jz8O144Z/QaQpU8DriE81pYh6YMs8buSFyNeMVi62VX2hLOcHP1kf94ia0IcicrBxg9ZHHiYn6aeyE72GTaxBokUDlym0hyWwKwJGLg/2uXPXLhHlvQb+zVbo8aeLnHDJu+lM66b3hF4vAm80kbDz5DcuyNxOadGocF4tTEty3zPgFBcnR12cOmA5BjQCKb/LA/qWsbTkPFkbMxHzxYPY/VD1gOUHVx+HSKTw7p/JfsHtPNVZw/4+9qygm6BMLkyHp5WV+NRX/yzzx9Xg2Dlg1/0qzAJuc/mTI25xpio15Ccn8IwjJFY99OjuklTk3EnhM8hE53biV29tVUyZAVUrgTePFDgjoxXfQO2jGjfpBKw4fQ2NLuC+yHahaGukhB8bsIJWsLi98CSnE/JNfM+WJAIXHQi+KYyzbnep0+hyftiWg==
  template:
    metadata:
      name: grafana-oauth-secret
      namespace: monitoring
