---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB6A56sfFP59ImDfr9mtnyn8PjXUUeqLrUybOZ8inQ5HOP04yulxiAowhbxVTgRvC7tZMiLkqCf+djTRglWVA8u3pw5jsyDLt95+RGEueWOnP3ZI/ITUIdkfylmUAbLVHnWHLMG67si4/VNBZ+IYnfTtiC5MwLWOG8KMbnzw016f5Q8EIJWbQIt9g8X3857PPzQrRUv5h55qvdQzWguBCWs/m1+LhbLt8YkS8AhIV/wxLSiSkclJNCDBsyFBqJxXD4zuefDUCdKUawd7RT88G3d81ucxPkicq8rIERWHyhI7W9F2WP+/Z/B1k+cjLLz1JAA8k0h7HE+W/WqWu4bFd2ndeO/bUwvPa36xv7kmnMeMkm5Qs4VrwTa3ktVNvsHSNl8cMPSpJn6xwGZGyuSqDO45zBiTPKXa9v3kusDeqXxZF0bGu0c79LYomd+2FNDKkkCnQ0BodMb79ibo+5xwNaQxzsGuCJha4rKzielbVdfyuRWcRmh5bhCimGBqsGwdQCzq6kdS+ktHHdaWA6bGNjilEvEb67lXQbpiSIZlYfXDCOzaAU5VT4YmBZlfZjP1dEfeu/VA0WKvttIcncWuEq69YV5VH9TGd1GWbmNXldpKC9UB5oI1s7nEdyYXkLQpaZ7kJgZPvK4wbPjBLCnq3Uz79uqrPEnS33+utCRusLilXfUXUJBjn+uWowoiimVX0Do4i3A3DVtEtQUaM+H+6j/
    admin-user: AgCJIewGsOhUvxxXfFzir2uckXmLN+90h38yxy6NdYBUzQCbaPYWMu6ggEnZidvPBWFQ/sLfMbjAyXvq/TDTh+fiTKQynYC20k0z83Nl/9yTAKu7bVqKbT+kyPON04IhNQQZdWN2LexIAxg1q95kgMzJ927lpjJ+boFQrNnUP+BsRVT8PNZxLohPdq92jYob3TZ3OUQKNsybNNbpADQ/tErLHUcY5DUo1cUpIkMGT+ns/eJQ8d41YhDzsYzJQSgeNXq5zKm3Td13TWyus59FMOx2wX6LNQ36c4a9G7nw6Du6pRfWxU+mR3nzRna1VoLdX1N00BzqOZ+ci68IyEDbVRxO+YNEGqX5CVfi6jdAjUprG3XRkXfPBNgk03hhi4++cL9SNYI+h3iUzi40+UfbP4yep3KSsSvliPaaCMhH5VDWa5Exe2WHAcxzl3gNBs4jLuHzRncNWLYwnbfRXf43kqTaTUk3hAH4H/uOx+4JkELSTbij3cddKK9QzbFUJSKFRn/+M2X9R/hF5Il8bV/S4W6Stb/yUnB8yH5b8sJknaHJ27kJR4Huik047rik+GkBkyUBSzoOMshZKlX/WuDAzw1VANQ6WUw+AJvPWh05weexkvQjI63f+vm7DjLX2JfYSsHwFGtQMgU/qNjKOSxcu7hdyrhZgW3J1zGI4gYQNv+M+NpYhKCf9KLGSbukJyU03MTMprg1sA==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
