{{- if .Values.persistence.local.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "openclaw.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.persistence.local.reclaimPolicy }}
  storageClassName: ""
  local:
    path: {{ .Values.persistence.local.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.persistence.local.node }}
{{- end }}
