---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: timescaledb-secret
  namespace: database
spec:
  encryptedData:
    postgres-password: AgCs7MBdVt8BHH0p8gZvqsnmXecPNRjnWCYYK14qmXDE7IdR/IOxFTJPmwZ+mBx9HHEe948KQymfFJHA6ModurYvXrga4QKoRz/uYWfhYmB5Gz0Fytd5jswj8EkCeEs4LAc9EefHaH2VdbDUosHBooK+qodmihsrPh2NnLKrRGDN8eJF0bMPdLISdcQYDWI8Sgsa9lD4NUfLQQJHZeOBrkwRcqpeMJCa1lSFDopi3LI+TnzHjmM9U6neEo5DGgUj60edWVe5KQQcKVwHKkxjzTEKmGiDpj1uSvrbbn3pXtGMMQ6MOme8Wg4WuhHpRmVI+r1LLpONdYenlqcgw/VNE1bnZjpdM+Mp3hHmr8qqSmY84NPo17VZX75M+u++XGMjHMXP81xBlZqlN1KPT/i9eRi/fq/Wo9Q6xVCn0EBmq6mgL3kHqb/PI/vC0tSdt5qWFPEKasexoO7Nsbl5GEw6uF3MM6eD78D+JgscItts14f5u0xAsXa9lfSeF8DIusO0/N+rLqNrSxEAOEYp10ELfWWhzI9eEDrs8zFBOZ18ovnxf4Pi8dD48ccP5EYRm04dOyHsKC9BkzZO5W490Y5VjkECl2Gtu91NqiDC8jHy6YFvAOhNwTCa++Xji1AI+f/0kg3w5iV57idWIaiaj7R5ZHBx62W+lh5s+0oaTLOgyvVX2uJRpxMYQEeQnuMu8HSJtQKUOcrg0dGO5r8ZVw==
  template:
    metadata:
      name: timescaledb-secret
      namespace: database
