image:
  repository: ghcr.io/openclaw/openclaw
  tag: "latest"
  pullPolicy: Always

gatewayToken:
  generate: true

ollama:
  api: "ollama"
  apiKey: "ollama-local"
  baseUrl: "http://192.168.1.7:11434"
  model: "qwen3:8b"

sandbox:
  mode: "non-main"
  scope: "session"
  workspaceAccess: "rw"

extraEnvVars:
  - name: OPENCLAW_DISABLE_BONJOUR
    value: "1"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

persistence:
  size: 10Gi
  local:
    enabled: true
    node: node1
    path: /home/tik/data/openclaw-standalone/
    reclaimPolicy: Retain

service:
  gatewayNodePort: 31789   # valid range: 30000-32767
  canvasNodePort: 31793

nodeSelector:
  kubernetes.io/hostname: node1
