---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-secret
  namespace: database
spec:
  encryptedData:
    kafka-admin-password: AgCrNHgVhbASJP2MluYmNhrnnL/ZQZhsHY3Awpu28Tf06h9bGotOqjjRwOAg7tz6Upze1saU+SXEFWR1CLwWJRPN+z8USogP7+dYUadn7zTWfOc9uZtAx6OMsTvmMyj3zfzjPBJ0YY6RtPDWVDvnUpOcVXvjbo1llQkT6QKeslTfDvAdudgfpmnSN4u4UtxgGIAdmI10utv1CDR3jrGRcop+AW8efaUQJxRJh4GnzyZRtEyzQNkF1bh3uk/5JMTHSCYK9aFwyD+XfqjKvdmtCzEP1Yl0Hg/bU4wDQN5OKFbyW7DZLu/p8OfjDDoTWEy7UxWd16k9VpXpsF7r2I38eY8l1pKlB5rKj49IFbQCFWhhQlAO9jujzSM+A/gaIPOQwCDfqCtNIoz9ceipNY6+6IhNa/Ps2wzXyDJD+wkNbZDISV3JsyVcqICSSSRgp0W6ETuKeWo2cE9dJIlACelfO6zK1XmZT9ypl5AxwTPbpfMX7UQUN7e8h7ZR8QC31hHLGYmG2+ufd+Cn986ahcQE6k4OpQO/vXKGVYK/73yK0TLZza1F/xli1WWrEs3x3LU9mSYt60t7Bfir5f5vat63N8GvLj5ejcpUUaFywGAZHX4eIi3O/iY+gC6dWziQzYHxkLVXE3ESXsql+qdxSbbLXfeyu20bVxGgGu1MtwTPQNmhOymDgPLSjHVDFqOcl8p7lM2Lb2lrHC3vL6nBwg==
  template:
    metadata:
      name: kafka-secret
      namespace: database
