---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-ui-oauth
  namespace: database
spec:
  encryptedData:
    client-secret: AgCCBGzdxmSGVewtt7ph3w2llUa0qXYu9wif1xb3uM+j937+YeYRZC9ONR+3vj7bHacGNvydTkyGOZaKUiFh29iIa/prw5zq8Dzaej0wQYSE3G9YCs1ZO5Qvi1WFze1TaR6/0X1+pwRISwgvxMK4IcOar2I9brrQwn9evVvCwt05DUREZR4sGVvsjZ9nZR29ZkR6eIZ568cyrkLSZd/bB2VsCH3Zf84WOkXs4KWGaytK4CjB02CNc/M+lZDDSvUsZWgL0oF8mTc5YBYbDu9WIier5VWPbGY+4bUxueDtVo3IwZzPMe08Irg1WQAwVUkwm2by40NhkJv6/gsYLPlljrpHCdlcjJ/Giej1Z6DPt4Xa1iip/bURELKrxBX6zyf0kW8Vk7FuieRkqKXLOyot1wuiQ9Knok7PuXIs2F9rNjHotjc9bW7HlGRw5A5HZd/hgyiXtBwCC34xuHoTWszXub5RyaYts6Gz27Ni4qIrvTWbicv5p3sE0CCC/CNjoIH0T0FjtNRyoczoYxWIAmZ+KfNUu/Hijo+clVGYIqlhfk5YNXF83Tuul6R2d6aclRqKLLllefCqztGRUMrBi1crAExfBxZYEcVryllvdC6hFfmLalK53mxBfA+cbKr3xIMNATqFdLF7k4SvEvUvmlbXTe/2tL2fYzEFl1uSWdzg1HiqDJXhg5Qd+gwTAj4olL+UNeDEVPHovcH+xRdP1XnL1V3oZuvJ3qXG9Q1ank14EmhUQgYLgQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: kafka-ui-oauth
      namespace: database
    type: Opaque
