---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-ui-oauth
  namespace: database
spec:
  encryptedData:
    client-secret: AgBsElCXF31b2wiKaM1HDKuPC7jGPfK4gjlazSSJVfLXnbBMxvTMLhiwqGl92XGKXhV0ZwpzeiaZdcThm+sTHmCWK+4jfw/dtaIkkI/Wud8A+qzNeLVY0/INH41VvUNP6KzmFhF9MQIZ3Z/TyJ5KflE4wj1Gm14H4SP4BKx9sCKwzWeYLAawugtIZpTgmpPxioP/wjaUr1we81G6HfGxZrliUdchMlQmCzf4tjDaX68wddr2rC+tRnwiI7RMAyq56tcNkaUGO5IB8cZDkISlQtehWroIOug9mtYkc8FpTuhF8imwJrVEQazY81LKH+RfRsbZsoIFTjr//l0Z78XudDRy30lMUhLmO0QpCCKOs1TSy25DdCmteLa00rZ0RzmBLbpCvUsyZt7BTB3ATmFx/BXfeOlGC4/zBGT2/flHC9bl7+tznin/ovdHoANRUXxBBUAQeS4UdgbXRKNpphw/bzDL425zF5lZM0Z89wlyWUMb2+ZyKLZ0BHTX3gBY+WyuDKUdC56N0AAW4RgyS2yLhfg24zv28IglI1zBPtGuGQTlbQowfyr2BhkItBnRgf5uIDq/ZeD/16ygfpBOTzHy3jQjnHoptJ78MhvEAsovoFA7q8SeY/bjV9v3PLebumnPiYT9+46eR6536Hd4+zY15XL20WUlPe+4gex9nUCciwDzHQpLoaHpa1dIz6zPiQUz8/8mz/PHZAoLr9oJ8ufEa/IwRXp1B0nUodpIYpfgziAA5w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: kafka-ui-oauth
      namespace: database
    type: Opaque
