---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: database
spec:
  encryptedData:
    postgres-password: AgC8K57DA/ngvneGSXYfhlHESgdRW4LDcWLEtR+7eoIngfdjHOTaANoUszmUm2mXAaRbp0tzPgr/3adUmaNsP/vRwvQ3033IzC4qKR5en4rbJNhEc55KDQQHPB8f4sB77/Tx2FfyO5jL9mMsblN+OUDuhj7Uic1+pC+Z+WE/vSKLstfeon9jogsUQkfi/cD3so4XMiTGBM4KGp46lv+Qvag0mm1DmtN35PNdx+U0PEPisylBjDtqhV2CyI16E7kSUrbSoabovapCKjVIXp5o96H8ck7HFUSIFhLQa9R919VRYcYQ2wwXW0wRwlp94Svwvh35LZ2LrIiTPVjPuRp8ZOP3QwBmiBTucRhe+tGAUqwgnwGF+3N6DkEoGH12RHBhJ1LD0nfDFo84f1l1+gPWgOCl6YZVlt89jNkigR8dam8dNvU9H1zDFKA8kvX1zOFQumXRMCEkc+sxUq/Ub+hh1G2DvR1ULPvzAMNNDaOTyLOLJ/8I30Ij8vZWfZXuOmj5ORIBIDD6idQ9TDpEYliO7a0+NUsO+74ICzkAPicxCdiAj4F4/KcJnwW2v5wWBiUhrL5F9AfPVV4/9K7zGhMZkBAbodJwA9wF6I3Bwud0Lmf4LQUc0djxUgLILZCb3XOjf61eKNHSDrw27mWPwfD08wXHvo5rIJfm35o6g0d5cv1rego0rUgHQ7H9Bc05oGDtUxbiyzrM8zbknDtQ9A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: postgres-secret
      namespace: database
