---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: database
spec:
  encryptedData:
    postgres-password: AgB1d1dP5+FAZtAp53rQkuB8gdeFhbP9I0vNINjGy8halbOtfLyW9laJIS2H0EGIngIyQ3cHvgb/2wsDuKWX7tAYoqtVnbXFKo+8GNQ56lu5u/ZKAYVYZsw8OdNtbHFUzYHnbd5CsyMSEDWwz1wRHZaQSkZ/Mc6TTM7xItqB/C7+WllOS5xHXkeAVTGgnO5ZXPNQdCwfPgfquCyQiu9mpfkk9mGCnSFJifi3XSquXP4Aptj3SGT4irka5fSP1PQY3jL3jfFhPw0f4oHITnZnov5Q985Yl9g5vvm0ukAoZYdPVN50jTM/WBAmjsA1EXYZkMAfFWwQbxQNikL69aEInH8iQT/cxlnUzSkBoSL9gY+fkYfAc3HEwM/e46TiYiHIxXlurqbo2uj49WLDU0QxiIyWRgDkuofZm3db7yVbqBlFwXCU22XpnrTWG1VviqdvtLel50AM8RIXFSMI094yx/p5dSnSTLi0QZZ81E8HqdQn7rhl1J/fV/zYWOi5bhYhCtds53THcemmTwrbvQMsdIpehwGjfRozxdSmhA8BQSRaUk1OHWQa2r6rJpFcxY9dwE3F6fnHrYrSWC+57FHyhmpHtnxO1JWr5rhBvl/xZ9wN6kV4myiEw+TLxXrl7AcJvTPV2n5UjFDHG0wzbIFr+9KXQFY875+wDM3/WTUxVysUUTcc0bFgb6hCihtw2TrEUPKevBzpQkia3e67Qw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: postgres-secret
      namespace: database
    type: Opaque
