# Development values for timescaledb.

# TimescaleDB Authentication
auth:
  existingSecret: "database-secret"
  secretKeys:
    adminPasswordKey: "postgres-password"

# TimescaleDB Configuration
config:
  timescaledbTelemetry: "off"

# Service configuration
service:
  type: NodePort
  port: 5432
  targetPort: 5432
  nodePort: 30433

# Persistence configuration
persistence:
  enabled: true
  size: 20Gi
  accessModes:
    - ReadWriteOnce
  useLocalVolume: true
  localPath: /home/tik/data/timescaledb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1

# Resources
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 1Gi
