replicaCount: 1

image:
  repository: tiktuzki/room-manager
  pullPolicy: Always
  tag: "latest"

config:
  applicationYaml: |
    spring:
      threads:
        virtual:
          enabled: true
      jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
      web:
        error:
          include-stacktrace: on_param
          include-message: always
      r2dbc:
        url: r2dbc:postgresql://postgres.database:5432/room_manager?currentSchema=prod
        username: postgres
        password: postgres
      flyway:
        enabled: true
        locations: classpath:db/migration
        url: jdbc:postgresql://postgres.database:5432/room_manager?currentSchema=prod
        user: postgres
      security:
        oauth2:
          client:
            registration:
              google:
                client-id: 759254302934-h0u67i38q8idqkvvjr5v0dmfmni59a0m.apps.googleusercontent.com
                client-secret:
                redirect-uri: http://localhost:3000
                scope:
                  - email
                  - profile
            provider:
              google:
                authorization-uri: https://accounts.google.com/o/oauth2/auth
                token-uri: https://oauth2.googleapis.com/token
                user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
                user-name-attribute: sub
          resourceserver:
            jwt:
              issuer-uri: https://accounts.google.com
    management:
      endpoint:
        health:
          probes:
            enabled: true
    logging:
      level:
        org:
          tiktuzki: debug
          springdoc: info
          springframework:
            web: info
          postgresql: debug
          flywaydb: debug
          flyway: debug
        io:
          r2dbc:
            postgresql: info

springBoot:
  javaOpts: ""
  profiles: "prod"

service:
  type: NodePort
  port: 8080
  nodePort: 32005

persistence:
  enabled: true
  size: 5Gi
  useLocalVolume: true
  localPath: /home/tik/data/room-manager/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 512Mi

## @param extraEnvVars Additional environment variables to set
extraEnvVars:
  - name: SPRING_R2DBC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: room-manager-secret
        key: spring-datasource-password
  - name: SPRING_FLYWAY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: room-manager-secret
        key: spring-datasource-password
  - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: room-manager-secret
        key: google-client-secret

## @param extraEnvVarsSecret Name of a secret containing additional environment variables
extraEnvVarsSecret: ""

serviceAccount:
  create: false
  automount: true
  annotations: { }
  name: ""
