{{- if and .Values.persistence.enabled .Values.persistence.local.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ollama.fullname" . }}-data-pv
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | default "20Gi" }}
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.local.reclaimPolicy | default "Retain" }}
  storageClassName: {{ .Values.persistence.storageClass | default "" | quote }}
  local:
    path: {{ .Values.persistence.local.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.persistence.local.node }}
{{- end }}
