replicaCount: 1

image:
  repository: tiktuzki/meeting-room
  pullPolicy: Always
  tag: "latest"

service:
  type: NodePort
  port: 3000
  nodePort: 32006

extraEnvVars:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: meeting-room-secret
        key: database-url
  - name: ADMIN_SECRET
    valueFrom:
      secretKeyRef:
        name: meeting-room-secret
        key: admin-secret
  - name: TELEGRAM_BOT_TOKEN
    valueFrom:
      secretKeyRef:
        name: meeting-room-secret
        key: telegram-bot-token
  - name: TELEGRAM_BOT_USERNAME
    value: genesis_hyper_bot
  - name: DISCORD_BOT_TOKEN
    valueFrom:
      secretKeyRef:
        name: meeting-room-secret
        key: discord-bot-token
  - name: DISCORD_APP_ID
    value: "1075266036829540442"
  - name: DISCORD_PUBLIC_KEY
    value: 2e0ad62059a8530a7cbc3a74f3afcf127af9a883d7317e6ed1477fd5fab07396
  - name: NEXT_PUBLIC_APP_URL
    value: "https://meeting.tiktuzki.com"

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 120
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 60
  timeoutSeconds: 150
  successThreshold: 1
  failureThreshold: 3

serviceAccount:
  create: false
  automount: true
  annotations: { }
  name: ""

ingress:
  enabled: true
  className: public
  hosts:
    - host: meeting.tiktuzki.com
      paths:
        - path: /
          pathType: Prefix
