---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neo-flagd-secret
  namespace: demo
spec:
  encryptedData:
    client-secret: AgAwKPSCzfilwTUd5SHjGUtM0xLPm6wJe8CMwHzN1hjBpsKTLCsbZnJD1ki2R+7aDpNB+YxR6xTWhBwvNpfqypyqAPD/JHMbh8+n3Qw92/EP5V9DJu7sMJz7o4JCugNphRDbCV/6pdtFFCXur1N9umZJOK8QdzpKqKSrhfEZvj3CEutcQaWr5JAZxXmspAidKh40yFOwkdNIHXGbw13Q4AoaskMateVf1FULMOhPJKOkiNgGy8VHyHQJKPF+GJEBJYfmcPpJiXSBHyWyRhGzpL/pzNnHTBsAUVFEaj9AtTXDCPgdSgxkQXdS/hj24sMzGyfl/0p6w3JxDhLJvLQszNV+zr8xkdDOkV5sbdVHcdZkSEIaBAtBmR+cfGKYdD/6vKM6y1mLUQD6GL0SD2HD12P5dU/tgGlrNXQV5SwopkXFVCFV4WMTo/ROOX++sZcuE/cwUwDUA4QgZMnCsI6kj688n5m93+HePEU6S8mFRHNK23B/wyMIovGdOJlqE0TXKb8ocASxLGozhxnh6I1JwFAyl13dExF9ilWzprHh6ggtBKpJjn551IWTJya8vsTgJwjwDs88dY1SIXJNE5Kuq2jnYEP3gDfAG4HqW0BrkpbDABBre/ARUX2d9XVoo68qeXhBi4ynfgx94pKxoOFZGZHGNn02uPJH/sEmHVpr4U6xkgTNGhV1nL9rC7Jd+2xbblb2g50EfB14HeJ+xXPO9JFvuKT/mAFBUKFfb1h3dk2W/g==
    pg-password: AgAuPJTn1dJvQfU8ZyD8IMpDxSkpaMAUjLMWWwLcfBu6W9JwbA8q0VIw+eJGwcHat4Gf6i9k/OywoNvDZskgHbuwHR4mDkMv1WAcpMP8gkPHMZWMCZVK2Zp+eOPO0ZHp0zBG0AHUqBHsSHDaCap2zJc3kRI9pFruRD92qXl67ZS0BXuAEjUsHufLEN+BrD4UEZ/OP6PcIi1Us46BMXdSrmEw/0xDbu0gYGhl7qwb1W3qPpCIuI/S2+nV7Gt8cBL0dXqF/NDr5WyAdxr6jAvVEDqkBwVjxHMIEc1TeDQQxrSTJaFbcAiuJ+SqZBGb4/ZFsE1y3YuL1otLnhGEJukn9sxHoKdhqMSdjSEdZFb0h6d2gnhBHOu1++aphI/98CIN97HzdcZEw70ilBPxkMFkpofRvn5KuuAiOJmBZ5ZTx1K2RyvgNtT1uXaMsiwLSQkbSZR0GB7OEu0AxKzW5MaTdIpErUmRGFTqdDJY9wZH8FHVmTHgy0ixaJef0FercYTZP/c6/LQL7ODhf/RD7L86QPgM+mQPJjXOtIBq1D4rWHUlCj+cmtM0UCu2yz4F0q+Z7FlZlaLWRLelF19MhrF6JqTc7ZqyE8+/xqPmVOcf/bCl0Z5JFgNHwlP6OUwde2ie4fuEX+noU50H8V/FXkMO3JMciBi01/9A8gp1XrQUo8GRPbtkj8aCEhkQZVEMsz9RM/hvDCEPdsI9s1eLeg==
  template:
    metadata:
      name: neo-flagd-secret
      namespace: demo
