---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgC7l0WiZsrQHxEvxZZ3+kx8Rbiqf+2eLo8WsIcAht7Ikb8QzVOItm92TVSm/eJfWC4liRPtwWDgwg8CURJrhoKHLvgVpk+lDyZ4sv7n4Cc0j3MKcN34359R5Fz5B6AyNXK7q46C4MozmxMBGhN8kig4uIqfsmGqBi/58Fi/REcb0S3hJZhbiHD0QmCtcQuNmRNR6xZpdAZz+6nyrWFunj0iygJD7kZPBpgBDvmQl/KttgXFghOg62clZjR50rkFhQwuJcncfYfzS21YDuuoNUwk4fVC5Q4/j1CIQ3KCj13YVdjqCkdF5PcmknebG8laL1p+ozGM+CnVHsN77KidYnA8TqGuGtekvh6J6sh82NVVgrL3fqGMHt9SJPH+MLAI/1e1BI72O0Wxg3xtkNOSrp9Q4emy5dEpcp6tJmdWnAVXmX57zcKQoFUz4ayKgOVRCYPTfkA/kMxW45rzIBpX+sxj8QzecvzbEyN+/aSm9Z9P+1si6cZ8IJYvccxLbRox8aa0v7lrLflWjU7VBiaEkhmIYHMwXi1l/M0SO7E4BVet+/BCJYZIjfcGi0H0t9z+nlV9Lqkvw8Qx5BdWmJBYogEhLj3KWvRgIuHZVpc/90lUSzju4KSxKchV4878hwHyGNZtfSi6GvovT7duYGoF68PEQbFkGkfgAtgn6GG2Y0ZDMxPidEprMESQmaSZt7Nk5lFkvuoRY3UGEaCUzQ==
  template:
    metadata:
      name: redis-secret
      namespace: database
