apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-sentinel.fullname" . }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ .Values.service.redisPort }}
      targetPort: redis
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.redisNodePort }}
      nodePort: {{ .Values.service.redisNodePort }}
      {{- end }}
    - name: sentinel
      port: {{ .Values.service.sentinelPort }}
      targetPort: sentinel
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.sentinelNodePort }}
      nodePort: {{ .Values.service.sentinelNodePort }}
      {{- end }}
  selector:
    {{- include "redis-sentinel.selectorLabels" . | nindent 4 }}
