persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  useLocalVolume: true
  localPath: /home/tik/data/tigerbeetle
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1

service:
  type: ClusterIP
  port: 3000
  nodePort: 30300
