{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "social-e.fullname" . }}-secret
  labels:
    {{- include "social-e.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.env.SECRET_KEY | quote }}
  {{- if .Values.secrets.GOOGLE_TTS_API_KEY }}
  GOOGLE_TTS_API_KEY: {{ .Values.secrets.GOOGLE_TTS_API_KEY | quote }}
  {{- end }}
  {{- if .Values.secrets.OPENAI_API_KEY }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  {{- end }}
  {{- if .Values.secrets.ANTHROPIC_API_KEY }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.ANTHROPIC_API_KEY | quote }}
  {{- end }}
  {{- if .Values.secrets.ELEVENLABS_API_KEY }}
  ELEVENLABS_API_KEY: {{ .Values.secrets.ELEVENLABS_API_KEY | quote }}
  {{- end }}
{{- end }}
