apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv-hub
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'git@github.com:TikTzuki/tiktuzki-charts.git'
    targetRevision: main
    path: charts/cv-hub
    helm:
      valueFiles:
        - values-dev.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
