apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw-helm
  namespace: devops
spec:
  destination:
    namespace: openclaw-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:TikTzuki/tiktuzki-gitops.git
    targetRevision: main
    path: charts/openclaw-helm
    helm:
      valueFiles:
        - values-dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
