apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: devops
spec:
  destination:
    name: keycloak
    namespace: infrastructure
    server: https://kubernetes.default.svc
  source:
    repoURL: oci://registry-1.docker.io/cloudpirates
    chart: keycloak
    targetRevision: 0.32.2
    helm:
      valueFiles:
        - values-dev.yaml

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
