apiVersion: v1
kind: Secret
metadata:
  name: room-manager-secret
  namespace: room-manager
type: Opaque
data:
  google-client-secret: R09DU1BYLXlKRzhCM0xhbFQ5NXRDaHlndTYyd1kwQjAtSGM=
  nextauth-secret: QUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUplcmU0SWQrZEx3Z2pSQU9RY0lCbTVvLzNQUkRsa2hUcHk0VlZZcE1JYmw=
  spring-datasource-password: MTIzNDU2Nzg=
