apiVersion: v1
kind: Secret
metadata:
  name: room-manager-secret
  namespace: room-manager
type: Opaque
data:
  spring-datasource-password: MTIzNDU2Nzg=
  google-client-secret: R09DU1BYLTd1RFh6QTltZm9iNFQ0ZUkyNHB2cGpqcks1WkMgLW4K
  nextauth-secret: QUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUplcmU0SWQrZEx3Z2pSQU9RY0lCbTVvLzNQUkRsa2hUcHk0VlZZcE1JYmwgLW4K
