apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: devops
spec:
  destination:
    name: 'timescaledb'
    namespace: database
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:TikTzuki/tiktuzki-gitops.git
    targetRevision: main
    path: charts/timescaledb
    helm:
      valueFiles:
        - values-dev.yaml

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
