# Development values for postgres.

# PostgreSQL configuration
postgres:
  database: postgres
  username: postgres
  existingSecret: postgres-secret
  existingSecretPasswordKey: postgres-password

# Persistence configuration
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 20Gi
  useLocalVolume: true
  localPath: /home/tik/data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1

# Service configuration
service:
  type: NodePort
  port: 5432
  nodePort: 30432

# Pod configuration
podAnnotations: { }
podLabels: { }
podSecurityContext: { }
securityContext: { }

# Resources
resources:
  limits:
    cpu: 1.5
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi
