{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "checkin.fullname" . }}-data
  labels:
    {{- include "checkin.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.persistence.storageClass | default "" | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "1Gi" }}
{{- end }}