#########################################################

replicaCount: 1
image:
  repository: registry.hub.docker.com/tiktzuki/fnb-uni-cms
  pullPolicy: Always
  tag: "uni-dev.a6a1.406"

imagePullSecrets: []
nameOverride: "fnb-uni-cms"
fullnameOverride: "fnb-uni-cms"
namespaceOverride: ""


service:
  type: ClusterIP
  ports:
  - name: http
    targetPort: 8080
    protocol: TCP
    port: 8080
  - name: rpc
    targetPort: 9090
    protocol: TCP
    port: 9090


deployment:
  command: ""
  args: ""
  annotations:
    keel.sh/policy: force

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

envFrom: []
  # - configMapRef:
  #     name: config
env:
  key_value:
    APPLICATION_DOMAIN_CUSTOMER_WEB: 'https://fnbdinerfe.tiktzuki.com'
    APPLICATION_DOMAIN_SERVER: 'https://api.tiktzuki.com/fnb-uni-cms'

    DATABASE_PASSWORD: 'P@ssword789'
    DATABASE_URL: 'jdbc:postgresql://timescaledb.database:5432/fnb-uni-cms-dev'
    DATABASE_USER: 'postgres'

    GRPC_CMS_CHANNEL_ADDRESS: 'static://fnb-cms.fnb:9090'

    JAEGER_ENABLED: 'true'
    JAEGER_HTTP_SENDER_URL: 'http://jaeger-collector.devops-tools:14268/api/traces'

    KEYCLOAK_CREDENTIALS_SECRET: ''
    KEYCLOAK_HOST: 'http://keycloak-21.keycloak'
    KEYCLOAK_ISSUER_URI: '${KEYCLOAK_HOST}/realms/fnb-uni-cms-dev'
    KEYCLOAK_JWT_SET_URI: '${KEYCLOAK_HOST}/realms/fnb-uni-cms-dev/protocol/openid-connect/certs'
    KEYCLOAK_REALM: 'fnb-uni-cms-dev'
    KEYCLOAK_RESOURCE: 'admin-cli'

    KLB_PAY_CLIENT_ID: '8501dfa7-3df6-4f80-aa5c-a041d3681740'
    KLB_PAY_ENCRYPT_KEY: '5C213CB10FB8AE399E6BBE8DDAC56B50CF799C228B41C34D3E20AD116D9161F0'
    KLB_PAY_SECRET_KEY: 'VO5z2MOXGugZc89HYYwd587RMC1anlJ51Sg/+jGhIO82mZP5os6vKK8VoGPZ8jGTo3CFZ9IfUydkXDfyRrumXebOHrP+cvrVAtL9eePoCImLrj9SXijCBLCHM4IrVFItYUSByxc/ryXmpyFaT19cuHOn+vqWb/ZD6QCwAW7r/Ek0ygafYVNnlJMfaLwFXnLDXUyBE0hC1xccZZRJXyPbUbZAgBA8coABymOchFtb9ABXwQf3hqtV9o9c1iQ6i56bQ3AP/CCpoDDI622KtdJ4ATjIWaYLLxRg6MkVC0f1uvn8/nMHKQ5KPg9VrqBZ99t4KiLGGfOUij1yWYo7ChHqjg=='
    KLB_PAY_TRANSACTION_LIFE_TIME: '10m'
    KLB_PAY_URL: 'https://api-staging.kienlongbank.co/pay'

    LOGIN_URL: 'https://kubesphere.tiktzuki.com/login'
    LOGGING_LEVEL_ORG_AXONFRAMEWORK: 'info'

    MINIO_ACCESS_KEY: 'qXr8tFwT86isPW4wEsO5'
    MINIO_BUCKET: 'fnb-uni-dev-uni-cms'
    MINIO_SECRET_KEY: 'Xt1pzNtnVCDOPiSjFjVjzItY8Ildklnfh1hppQKY'
    MINIO_URL: 'http://minio-api.public:10106'
    MINIO_CDN_URL: 'https://minio.tiktzuki.com'

    NOTIFO_API_KEY: 'rrvky6fblp58wkga2paxfhwtmglhpkcmryuibxzjh8mx'
    NOTIFO_APP_ID: '199f9a13-4b5c-4454-9404-559ec6087cd5'
    NOTIFO_URL: 'https://notify-dev.unicloud.com.vn'

    RABBITMQ_HOST: 'rabbitmq.public-queue'
    RABBITMQ_PASSWORD: 'guest'
    RABBITMQ_PORT: '5672'
    RABBITMQ_USERNAME: 'guest'
    RABBITMQ_VHOST: 'uni-dev'

    REDIS_DATABASE: '7'
    REDIS_HOST: 'redis-master.fnb.svc.cluster.local'
    REDIS_PASSWORD: 'P@ssword789'
    REDIS_PORT: '6379'

    SERVER_PATH: /uni-dev/fnb-uni-cms

    SMS_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6ImFkbWluIiwiaWF0IjoxNTE2MjM5MDIyfQ.wuHYbExf8mo06-RveSfS2GZt6MOR1_ahgU7T58HFdxQ'
    SMS_URL: 'https://sms.sunshineapp.vn/api'

    SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
    SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: 'false'
    SPRING_JPA_PROPERTIES_JDBC_BATCH_SIZE: '100'
    SPRING_PROFILES_ACTIVE: 'dev-group'

    TEMPLATE_RESET_PASSWORD: 'reset-password'
    TEMPLATE_VERIFY_EMAIL: 'verify-email'

    WEBSOCKET_HOST: 'rabbitmq.public-queue'
    WEBSOCKET_PASSWORD: 'guest'
    WEBSOCKET_PORT: '61613'
    WEBSOCKET_USERNAME: 'guest'
    WEBSOCKET_VHOST: 'uni-dev'

  name_value:

persistence:
  enabled: false

  create:
    enabled: false
    mountPath: /root
    accessMode: ReadWriteOnce
    size: 50Mi
    storageClass: local

  existingClaim:
    enabled: false
    volumeMounts: 
      - name: "rd"
        mountPath: "/app"
      - name: "rd-config"
        mountPath: /scripts/setup.sh
    volumes:
      - name: "rd"
        persistentVolumeClaim:
          claimName: "rd"
      - name: "rd-configmap"
        configMap:
          name: "config"
          defaultMode: 0777


#########################################################

initContainers: []
  # - name: init-test
  #   image: ubuntu:20.04
  #   command: ['echo', 'hello-world']

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000



ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

tolerations: []

affinity: {}

livenessProbe:
  enabled: true

  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 120
  successThreshold: 1
  failureThreshold: 3

  setting:
    # exec:
    #   command: 
    #   - cat
    #   - /tmp/health
    httpGet:
      path: /actuator/health
      port: http
    #   httpHeaders: []
    # tcpSocket:
    #   port: http

    
readinessProbe:
  enabled: true

  initialDelaySeconds: 25
  periodSeconds: 2
  timeoutSeconds: 150
  successThreshold: 1
  failureThreshold: 3

  setting:
    # exec:
    #   command: 
    #   - cat
    #   - /tmp/health
    httpGet:
      path: /actuator/health
      port: http
    #   httpHeaders: []
    # tcpSocket:
    #   port: http


startupProbe:
  enabled: false

  initialDelaySeconds: 
  periodSeconds: 
  timeoutSeconds: 
  successThreshold: 
  failureThreshold: 

  setting:
    #exec:
      # command: 
      # - cat
      # - /tmp/health
    # httpGet:
    #   path: /health
    #   port: http
    #   httpHeaders: []
    # tcpSocket:
    #   port: http
