{{- if .Values.persistence.local.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openclaw-standalone.fullname" . }}-data
  labels:
    {{- include "openclaw-standalone.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
